import type { Action } from '$lib/types/action';
import { GameAgent } from '$lib/ai/agents/gameAgent';
import type { GameActionState } from '$lib/types/actions';
import type { InventoryState } from '$lib/types/inventory';
import type { PlayerCharactersGameState, PlayerCharactersIdToNamesMap } from '$lib/types/players';
import { getLevelUpCostObject } from '$lib/game/resourceUtils';
import { getPromptForGameMasterNotes, getCraftingPrompt } from '$lib/ai/agents/gameAgentPrompts';
import type { LLMMessage, SystemInstructionsState } from '$lib/ai/llm';
import type { Story } from '$lib/ai/agents/storyAgent';
import { getSafetyLevelFromStory } from '$lib/utils/contentRatingToSafety';
import { saveSnapshotBeforeAction, validateUndoConsistency } from '$lib/state/gameActionHelper';
import type { CharacterDescription } from '$lib/ai/agents/characterAgent';
import type { CharacterStats, NPCState } from '$lib/ai/agents/characterStatsAgent';
import { CombatAgent } from '$lib/ai/agents/combatAgent';
import type { ActionAgent } from '$lib/ai/agents/actionAgent';
import type { SummaryAgent } from '$lib/ai/agents/summaryAgent';
// Campaign removed
import type { EventAgent, EventEvaluation, CharacterChangedInto } from '$lib/ai/agents/eventAgent';
import { ConversationStateManager } from '$lib/game/state/conversationState.svelte';
import * as gameLogic from '../logic/gameLogic';
import * as npcLogic from '../npc/npcLogic';
import { getLatestStoryMessagesFromHistory } from '../memory/messages';
import { CombatAgent as CombatAgentStatic } from '$lib/ai/agents/combatAgent';
import { stringifyPretty } from '$lib/util.svelte';
import type { ThoughtsState } from '$lib/util.svelte';
import type { DiceRollResult } from '../logic/diceRollLogic';
import {
	getSkillIfApplicable,
	applyCharacterChange,
	addCharacterToPlayerCharactersIdToNamesMap
} from '../logic/characterLogic';
import { getXPNeededForLevel, applyLevelUp } from '../logic/levelLogic';
import { refillResourcesFully } from '../logic/resourceLogic';
import type { AiLevelUp, Ability } from '$lib/ai/agents/characterStatsAgent';
import type { ModalManager } from '../ui/modalManager.svelte';
import type { GameTime } from '$lib/types/gameTime';
import { addMinutesToGameTime, normalizeGameTime } from '../logic/timeLogic';
import { buildPresenceContinuityPrompt, computePresenceContinuity } from '$lib/game/memory/npcPresenceManager';

/**
 * Utility function to create game time with proper defaults
 * Improves code reusability and reduces duplication
 */
function createGameTimeFromAI(initialGameTime: any): GameTime {
	return {
		day: initialGameTime.day,
		dayName: initialGameTime.dayName,
		month: initialGameTime.month,
		monthName: initialGameTime.monthName,
		year: initialGameTime.year,
		hour: initialGameTime.hour,
		minute: initialGameTime.minute,
		timeOfDay: initialGameTime.timeOfDay as GameTime['timeOfDay'],
		season: initialGameTime.season || 'spring',
		weather: initialGameTime.weather || {
			type: 'clear',
			intensity: 'light',
			description: 'Pleasant weather'
		}
	};
}

/**
 * Utility function to log time progression with consistent formatting
 * Improves maintainability and reduces code duplication
 */
function logTimeProgression(minutesPassed: number, explanation?: string): void {
	console.log(`⏰ Time elapsed: ${minutesPassed}min - ${explanation || 'Time progressed'}`);
}

/**
 * Utility function to log initial time with consistent formatting
 * Improves maintainability and reduces code duplication
 */
function logInitialTime(gameTime: GameTime, explanation?: string): void {
	const timeString = `${gameTime.hour}:${gameTime.minute.toString().padStart(2, '0')}`;
	console.log(
		`🎯 Initial time generated by AI: ${gameTime.dayName} ${gameTime.day} ${gameTime.monthName} ${gameTime.year}, ${timeString} (${gameTime.timeOfDay})`
	);
	if (explanation) {
		console.log(`📅 Explication: ${explanation}`);
	}
}

export type ControllerCtx = {
	agents: {
		gameAgent: GameAgent;
		summaryAgent: SummaryAgent;
		actionAgent: ActionAgent;
		combatAgent: CombatAgent;
		// campaignAgent removed
		eventAgent: EventAgent;
		characterAgent: import('$lib/ai/agents/characterAgent').CharacterAgent;
		characterStatsAgent: import('$lib/ai/agents/characterStatsAgent').CharacterStatsAgent;
	};
	conversationManager?: ConversationStateManager;
	state: {
		// primitives or getters to always read latest
		getCurrentGameActionState: () => GameActionState;
		isGameEnded: { value: boolean };
		isAiGeneratingState: { get: () => boolean; set: (v: boolean) => void };
		didAIProcessActionState: { get: () => boolean; set: (v: boolean) => void };
		resetShowXLastStoryProgressions: () => void;
		storyChunkReset: () => void;

		playerCharacterId: string;
		playerCharactersGameState: { value: PlayerCharactersGameState };
		playerCharactersIdToNamesMapState: { value: PlayerCharactersIdToNamesMap };
		npcState: { value: NPCState };
		inventoryState: { value: InventoryState };
		systemInstructionsState: { value: SystemInstructionsState };
		storyState: { value: Story };
		historyMessagesState: { value: LLMMessage[] };
		characterActionsState: { value: Action[] };
		thoughtsState: { value: ThoughtsState };
		gameActionsState: { value: GameActionState[] };
		characterState: { value: CharacterDescription };
		characterStatsState: { value: CharacterStats };
		eventEvaluationState: { value: EventEvaluation };
		relatedStoryHistoryState: {
			value: { relatedDetails: Array<{ storyReference: string; relevanceScore: number }> };
		};
		relatedActionHistoryState: { value: string[] };
		customMemoriesState: { value: string | undefined };
		customGMNotesState: { value: string | undefined };
		additionalStoryInputState: { value: string };
		additionalActionInputState: { value: string };
		chosenActionState: { value: Action };
		gameSettingsState: { value: any };
		gameTimeState: { value: GameTime | null };
		useDynamicCombat: { value: boolean };
	};
	modals: ModalManager;
	helpers: {
		addAdditionalStoryInput: (
			action: Action,
			additionalStoryInput: string
		) => Promise<string>;
		// campaign GM notes removed
		openDiceRollDialog: () => void;
		handleError: (e: string) => void;
		resetStatesAfterActionProcessed: () => void;
		checkGameEnded: () => Promise<void>;
		getRelatedHistoryForStory: () => void;
		checkForNewNPCs: (newState: GameActionState) => void;
		checkForLevelUp: () => void;
		onStoryStreamUpdate: (chunk: string, isComplete: boolean) => void;
		onThoughtStreamUpdate: (chunk: string, isComplete: boolean) => void;
		applyGameEventEvaluation: (evaluated: any) => void;
		getCurrentDiceRollResult: () => DiceRollResult | undefined;
		setGMQuestion: (text: string) => void;
		setCustomDiceRollNotation: (notation: string) => void;
		setCustomActionImpossibleReason: (
			reason: 'not_enough_resource' | 'not_plausible' | undefined
		) => void;
		setItemForSuggestActions: (item: any) => void;
		setLevelUpState: (state: {
			buttonEnabled: boolean;
			dialogOpened: boolean;
			playerName: string;
		}) => void;
	};
	skills: {
		skillsProgressionForCurrentActionState: {
			get: () => number | undefined;
			set: (v: number | undefined) => void;
		};
		addSkillProgression: (skillName: string, progression: number) => void;
		advanceSkillIfApplicable: (skillName: string) => void;
		determineProgressionForAction: (action: Action, existing?: number) => number;
		addSkillsIfApplicable: (actions: Action[]) => void;
	};
};

export function createGameController(ctx: ControllerCtx) {
	async function getActionPromptForCombat(playerAction: Action) {
		const currentGameActionState = ctx.state.getCurrentGameActionState();
		const allNpcsDetailsAsList = gameLogic
			.getAllTargetsAsList(currentGameActionState.currently_present_npcs)
			.map((technicalId) => ({ technicalId, ...ctx.state.npcState.value[technicalId] }));

		const determinedActionsAndStatsUpdate = await ctx.agents.combatAgent.generateActionsFromContext(
			playerAction,
			ctx.state.playerCharactersGameState.value[ctx.state.playerCharacterId],
			ctx.state.inventoryState.value,
			allNpcsDetailsAsList,
			ctx.state.systemInstructionsState.value.generalSystemInstruction,
			ctx.state.systemInstructionsState.value.combatAgentInstruction,
			getLatestStoryMessagesFromHistory(ctx.state.historyMessagesState.value),
			ctx.state.storyState.value,
			getSafetyLevelFromStory(ctx.state.storyState.value)
		);

		gameLogic.applyGameActionState(
			ctx.state.playerCharactersGameState.value,
			ctx.state.playerCharactersIdToNamesMapState.value,
			ctx.state.npcState.value,
			ctx.state.inventoryState.value,
			JSON.parse(JSON.stringify(determinedActionsAndStatsUpdate))
		);
		// No manual reactivity trigger needed with useHybridLocalStorage

		const aliveNPCs = allNpcsDetailsAsList
			.filter((npc: any) => npc?.resources && npc.resources.current_hp > 0)
			.map((npc: any) => npc.technicalId);

		const additionalStoryInput = CombatAgentStatic.getAdditionalStoryInput(
			determinedActionsAndStatsUpdate.actions,
			[],
			aliveNPCs,
			ctx.state.playerCharactersGameState.value
		);

		return { additionalStoryInput, determinedActionsAndStatsUpdate } as const;
	}

	async function getCombatAndNPCState(action: Action) {
		const isContinue = (action?.text || '').trim().toLowerCase() === 'continue the tale';
		const currentGameActionState = ctx.state.getCurrentGameActionState();
		let additionalStoryInput = '';
		let allCombatDeterminedActionsAndStatsUpdate: any | undefined;
		if (
			!isContinue &&
			!ctx.state.isGameEnded.value &&
			currentGameActionState.is_character_in_combat
		) {
			if (ctx.state.useDynamicCombat.value) {
				const combatObject = await getActionPromptForCombat(action);
				additionalStoryInput += combatObject.additionalStoryInput;
				allCombatDeterminedActionsAndStatsUpdate = combatObject.determinedActionsAndStatsUpdate;
			}
		}
		const deadNPCs = npcLogic.removeDeadNPCs(ctx.state.npcState.value);
		additionalStoryInput += CombatAgentStatic.getNPCsHealthStatePrompt(deadNPCs);
		return { additionalStoryInput, allCombatDeterminedActionsAndStatsUpdate } as const;
	}

	async function prepareAdditionalStoryInput(action: Action, initialAdditionalStoryInput: string) {
		const currentGameActionState = ctx.state.getCurrentGameActionState();
		const isContinue = (action?.text || '').trim().toLowerCase() === 'continue the tale';
		let additionalStoryInput = initialAdditionalStoryInput || '';
		const combatAndNPCState = await getCombatAndNPCState(action);
		additionalStoryInput += combatAndNPCState.additionalStoryInput;

		// Presence continuity: add strict rules to prevent NPCs speaking when absent and ensure party continuity
		try {
			const previousState = ctx.state.gameActionsState.value[ctx.state.gameActionsState.value.length - 1];
			const continuity = computePresenceContinuity(previousState, ctx.state.npcState.value);
			additionalStoryInput += '\n' + buildPresenceContinuityPrompt(continuity);
		} catch (e) {
			console.warn('Presence continuity prompt generation failed:', e);
		}

		additionalStoryInput = await ctx.helpers.addAdditionalStoryInput(
			action,
			additionalStoryInput
		);

		if (ctx.state.customGMNotesState.value) {
			additionalStoryInput += getPromptForGameMasterNotes([ctx.state.customGMNotesState.value]);
		}

		if (!isContinue && action.type?.toLowerCase() === 'crafting') {
			additionalStoryInput += getCraftingPrompt();
		}
		// Side-effects additions informed by latest dice roll result (if any)
		if (!isContinue) {
			additionalStoryInput = gameLogic.addAdditionsFromActionSideeffects(
				action,
				additionalStoryInput,
				ctx.state.gameSettingsState.value.randomEventsHandling,
				currentGameActionState.is_character_in_combat,
				(ctx.helpers.getCurrentDiceRollResult() ?? 'regular_success') as DiceRollResult
			);
		}
		if (!additionalStoryInput.includes('sudo')) {
			additionalStoryInput +=
				'\n\nBefore responding always review the system instructions and apply the given rules.';
		}
		ctx.state.additionalStoryInputState.value = additionalStoryInput;
		return { finalAdditionalStoryInput: additionalStoryInput, combatAndNPCState } as const;
	}

	async function processStoryProgression(
		action: Action,
		additionalStoryInput: string,
		relatedHistory: string[],
		isCharacterInCombat: boolean,
		combatAndNPCState: {
			additionalStoryInput: string;
			allCombatDeterminedActionsAndStatsUpdate?: any;
		}
	) {
		// Get safety level from the story's content rating
		const safetyLevel = getSafetyLevelFromStory(ctx.state.storyState.value);

		const { newState, updatedHistoryMessages } =
			await ctx.agents.gameAgent.generateStoryProgression(
				ctx.helpers.onStoryStreamUpdate,
				ctx.helpers.onThoughtStreamUpdate,
				action,
				additionalStoryInput,
				ctx.state.systemInstructionsState.value.generalSystemInstruction,
				ctx.state.systemInstructionsState.value.storyAgentInstruction,
				isCharacterInCombat ? ctx.state.systemInstructionsState.value.combatAgentInstruction : '',
				ctx.state.historyMessagesState.value,
				ctx.state.storyState.value,
				ctx.state.characterState.value,
				ctx.state.playerCharactersGameState.value,
				ctx.state.inventoryState.value,
				ctx.state.npcState.value,
				relatedHistory,
				ctx.state.gameSettingsState.value,
				ctx.state.gameTimeState.value || null, // Pass null if no time defined yet
				safetyLevel // Pass the safety level from tale's content rating
			);

		if (!newState?.story) return;

		// Process time progression from gameAgent response - optimized with utility functions
		if (newState.time_passed_minutes && ctx.state.gameTimeState.value) {
			try {
				ctx.state.gameTimeState.value = addMinutesToGameTime(
					ctx.state.gameTimeState.value,
					newState.time_passed_minutes
				);
				logTimeProgression(newState.time_passed_minutes, newState.time_passed_explanation);
			} catch (error) {
				console.error('Time progression failed:', error);
			}
		}

		// Process initial time generated by AI - optimized with utility functions
		if (newState.initial_game_time) {
			try {
				const newGameTime = createGameTimeFromAI(newState.initial_game_time);
				ctx.state.gameTimeState.value = normalizeGameTime(newGameTime);
				logInitialTime(newGameTime, newState.initial_game_time.explanation);
			} catch (error) {
				console.error('Initial time setting failed:', error);
			}
		}

		ctx.helpers.checkForNewNPCs(newState);
		npcLogic.addNPCNamesToState(newState.currently_present_npcs, ctx.state.npcState.value);

		if (combatAndNPCState.allCombatDeterminedActionsAndStatsUpdate) {
			newState.stats_update =
				combatAndNPCState.allCombatDeterminedActionsAndStatsUpdate?.stats_update ||
				newState.stats_update;
			gameLogic.applyInventoryUpdate(ctx.state.inventoryState.value, newState);
		} else {
			// Apply resources directly to useHybridLocalStorage state - no complex reactivity needed
			gameLogic.applyGameActionState(
				ctx.state.playerCharactersGameState.value,
				ctx.state.playerCharactersIdToNamesMapState.value,
				ctx.state.npcState.value,
				ctx.state.inventoryState.value,
				JSON.parse(JSON.stringify(newState))
			);
		}
		console.log('new state', stringifyPretty(newState));
		ctx.state.historyMessagesState.value = updatedHistoryMessages;

		const skillName = getSkillIfApplicable(ctx.state.characterStatsState.value, action);
		if (skillName) {
			const existing = ctx.skills.skillsProgressionForCurrentActionState.get();
			const progression = ctx.skills.determineProgressionForAction(action, existing);
			ctx.skills.skillsProgressionForCurrentActionState.set(progression);
			ctx.skills.addSkillProgression(skillName, progression);
			ctx.skills.advanceSkillIfApplicable(skillName);
		}

		ctx.helpers.resetStatesAfterActionProcessed();

		const { newHistory } = await ctx.agents.summaryAgent.summarizeStoryIfTooLong(
			ctx.state.historyMessagesState.value
		);
		ctx.state.historyMessagesState.value = newHistory;
		ctx.state.gameActionsState.value = [
			...ctx.state.gameActionsState.value,
			{ ...newState, id: ctx.state.gameActionsState.value.length }
		];
		ctx.state.storyChunkReset();

		// 🗣️ DIALOGUE TRACKING: Track new conversations to prevent future repetitions
		if (ctx.conversationManager && newState.story) {
			try {
				const conversationSummary = await ctx.agents.gameAgent.dialogueTracker.extractConversationSummary(
					newState.story,
					ctx.state.gameActionsState.value.length - 1
				);

				if (conversationSummary) {
					ctx.conversationManager.addConversation(conversationSummary);
					console.log('📝 Conversation tracked:', conversationSummary.conversation_id);
				}
			} catch (error) {
				console.warn('Failed to track conversation:', error);
				// Non-fatal error, continue normal flow
			}
		}

		await ctx.helpers.checkGameEnded();

		if (!ctx.state.isGameEnded.value) {
			// Evaluate special events triggered by the new story progression
			try {
				const storyHistory = ctx.state.gameActionsState.value
					.map((ga) => ga.story)
					.filter((s): s is string => !!s);
				storyHistory.push(newState.story);
				const currentAbilitiesNames = (
					ctx.state.characterStatsState.value?.spells_and_abilities || []
				)
					.map((a) => a.name)
					.filter((n): n is string => !!n);
				const { thoughts, event_evaluation } = await ctx.agents.eventAgent.evaluateEvents(
					storyHistory,
					currentAbilitiesNames
				);
				ctx.state.thoughtsState.value.eventThoughts = thoughts || '';
				if (event_evaluation) {
					ctx.helpers.applyGameEventEvaluation(event_evaluation);
				}
			} catch (e) {
				// Non-fatal: log and proceed
				console.warn('Event evaluation failed:', e);
			}

			ctx.helpers.getRelatedHistoryForStory();
			// Regenerate actions for next turn
			const safetyLevel = getSafetyLevelFromStory(ctx.state.storyState.value);
			const { thoughts, actions } = await ctx.agents.actionAgent.generateActions(
				ctx.state.getCurrentGameActionState(),
				ctx.state.historyMessagesState.value,
				ctx.state.storyState.value,
				ctx.state.characterState.value,
				ctx.state.characterStatsState.value,
				ctx.state.inventoryState.value,
				ctx.state.systemInstructionsState.value.generalSystemInstruction,
				ctx.state.systemInstructionsState.value.actionAgentInstruction,
				relatedHistory,
				ctx.state.gameSettingsState.value?.aiIntroducesSkills,
				newState.is_character_restrained_explanation,
				ctx.state.additionalActionInputState.value,
				safetyLevel
			);
			// Persist regenerated actions and thoughts so UI can render them
			if (actions) {
				ctx.state.characterActionsState.value = actions;
				ctx.skills.addSkillsIfApplicable(actions);
			}
			if (typeof thoughts === 'string') {
				ctx.state.thoughtsState.value.actionsThoughts = thoughts;
			}
			ctx.helpers.checkForLevelUp();
		}
	}

	async function regenerateActions() {
		ctx.state.characterActionsState.value = [];
		const { getRelatedHistory } = await import('../memory/memoryLogic');
		const relatedHistory = await getRelatedHistory(
			ctx.agents.summaryAgent,
			undefined,
			undefined,
			ctx.state.relatedStoryHistoryState.value,
			ctx.state.customMemoriesState.value
		);
		const safetyLevel = getSafetyLevelFromStory(ctx.state.storyState.value);
		const { thoughts, actions } = await ctx.agents.actionAgent.generateActions(
			ctx.state.getCurrentGameActionState(),
			ctx.state.historyMessagesState.value,
			ctx.state.storyState.value,
			ctx.state.characterState.value,
			ctx.state.characterStatsState.value,
			ctx.state.inventoryState.value,
			ctx.state.systemInstructionsState.value.generalSystemInstruction,
			ctx.state.systemInstructionsState.value.actionAgentInstruction,
			relatedHistory,
			ctx.state.gameSettingsState.value?.aiIntroducesSkills,
			ctx.state.getCurrentGameActionState().is_character_restrained_explanation,
			ctx.state.additionalActionInputState.value,
			safetyLevel
		);
		ctx.state.characterActionsState.value = actions || [];
		if (typeof thoughts === 'string') {
			ctx.state.thoughtsState.value.actionsThoughts = thoughts;
		}
		if (actions) ctx.skills.addSkillsIfApplicable(actions);
	}

	async function confirmCharacterChangeEvent(
		changedInto: CharacterChangedInto,
		confirmed: boolean
	) {
		ctx.state.eventEvaluationState.value.character_changed!.showEventConfirmationDialog = false;
		if (confirmed === undefined) return;
		if (confirmed) {
			ctx.state.isAiGeneratingState.set(true);
			const { transformedCharacter, transformedCharacterStats } = await applyCharacterChange(
				changedInto,
				JSON.parse(JSON.stringify(ctx.state.storyState.value)),
				JSON.parse(JSON.stringify(ctx.state.characterState.value)),
				JSON.parse(JSON.stringify(ctx.state.characterStatsState.value)),
				ctx.agents.characterAgent,
				ctx.agents.characterStatsAgent
			);

			if (transformedCharacter) {
				addCharacterToPlayerCharactersIdToNamesMap(
					ctx.state.playerCharactersIdToNamesMapState.value,
					ctx.state.playerCharacterId,
					transformedCharacter.name
				);
				ctx.state.characterState.value = transformedCharacter;
			}
			if (transformedCharacterStats) {
				ctx.state.characterStatsState.value = transformedCharacterStats;
				await regenerateActions();
				ctx.state.additionalStoryInputState.value +=
					'\n After transformation make sure that stats_update refer to the new resources from now on!\n' +
					stringifyPretty(ctx.state.characterStatsState.value.resources);
			}

			// apply new resources
			// Ensure character state exists before accessing XP
			if (!ctx.state.playerCharactersGameState.value[ctx.state.playerCharacterId]) {
				ctx.state.playerCharactersGameState.value[ctx.state.playerCharacterId] = {
					...JSON.parse(JSON.stringify(ctx.state.characterStatsState.value.resources)),
					XP: { current_value: 0, max_value: 0, game_ends_when_zero: false }
				} as any;
			}

			ctx.state.playerCharactersGameState.value[ctx.state.playerCharacterId] = {
				...JSON.parse(JSON.stringify(ctx.state.characterStatsState.value.resources)),
				XP: ctx.state.playerCharactersGameState.value[ctx.state.playerCharacterId].XP
			} as any;
			const { updatedGameActionsState, updatedPlayerCharactersGameState } = refillResourcesFully(
				JSON.parse(JSON.stringify(ctx.state.characterStatsState.value.resources)),
				ctx.state.playerCharacterId,
				ctx.state.characterState.value.name,
				JSON.parse(JSON.stringify(ctx.state.gameActionsState.value)),
				JSON.parse(JSON.stringify(ctx.state.playerCharactersGameState.value))
			);
			ctx.state.gameActionsState.value = updatedGameActionsState;
			ctx.state.playerCharactersGameState.value = updatedPlayerCharactersGameState;
		}
		ctx.state.eventEvaluationState.value.character_changed!.aiProcessingComplete = true;
		ctx.state.isAiGeneratingState.set(false);
	}

	function confirmAbilitiesLearned(abilities?: Ability[]) {
		ctx.state.eventEvaluationState.value.abilities_learned!.showEventConfirmationDialog = false;
		if (!abilities) return;
		ctx.state.eventEvaluationState.value.abilities_learned!.aiProcessingComplete = true;
		if (abilities.length === 0) return;
		console.log('Added new abilities:', stringifyPretty(abilities));
		ctx.state.characterStatsState.value = {
			...ctx.state.characterStatsState.value,
			spells_and_abilities: [
				...ctx.state.characterStatsState.value.spells_and_abilities,
				...abilities
			]
		} as any;
	}

	async function sendAction(action: Action, rollDice = false) {
		try {
			// Save snapshot before processing action for undo functionality
			saveSnapshotBeforeAction();

			// Validate undo consistency periodically (every 10th action)
			const gameActions = ctx.state.gameActionsState.value;
			if (gameActions.length % 10 === 0) {
				validateUndoConsistency();
			}

			// Normalize special neutral Continue action to avoid carrying over previous context
			const isContinue = (action?.text || '').trim().toLowerCase() === 'continue the tale';
			if (isContinue) {
				// Clear any leftover user additions and related action history so the AI truly "continues"
				ctx.state.additionalStoryInputState.value = '';
				ctx.state.additionalActionInputState.value = '';
				ctx.state.relatedActionHistoryState.value = [];
				// Ensure action does not accidentally inherit fields from elsewhere
				action = {
					characterName: ctx.state.characterState.value.name,
					text: 'Continue The Tale'
				};
			}

			if (rollDice) {
				if (ctx.state.relatedActionHistoryState.value.length === 0) {
					const { getRelatedHistory } = await import('../memory/memoryLogic');
					ctx.state.relatedActionHistoryState.value = await getRelatedHistory(
						ctx.agents.summaryAgent,
						action,
						ctx.state.gameActionsState.value,
						ctx.state.relatedStoryHistoryState.value,
						ctx.state.customMemoriesState.value
					);
				}
				ctx.helpers.openDiceRollDialog();
			} else {
				ctx.state.resetShowXLastStoryProgressions();
				ctx.state.isAiGeneratingState.set(true);

				const { finalAdditionalStoryInput, combatAndNPCState } = await prepareAdditionalStoryInput(
					action,
					ctx.state.additionalStoryInputState.value
				);
				if (ctx.state.relatedActionHistoryState.value.length === 0) {
					const { getRelatedHistory } = await import('../memory/memoryLogic');
					ctx.state.relatedActionHistoryState.value = await getRelatedHistory(
						ctx.agents.summaryAgent,
						action,
						ctx.state.gameActionsState.value,
						ctx.state.relatedStoryHistoryState.value,
						ctx.state.customMemoriesState.value
					);
				}
				ctx.state.didAIProcessActionState.set(false);
				await processStoryProgression(
					action,
					finalAdditionalStoryInput,
					ctx.state.relatedActionHistoryState.value,
					ctx.state.getCurrentGameActionState().is_character_in_combat,
					combatAndNPCState
				);
				ctx.state.didAIProcessActionState.set(true);
				ctx.state.isAiGeneratingState.set(false);
			}
		} catch (e) {
			ctx.state.isAiGeneratingState.set(false);
			ctx.helpers.handleError(e as string);
		}
	}

	async function generateActionFromCustomInput(action: Action) {
		ctx.state.isAiGeneratingState.set(true);
		const { getRelatedHistory } = await import('../memory/memoryLogic');
		ctx.state.relatedActionHistoryState.value = await getRelatedHistory(
			ctx.agents.summaryAgent,
			action,
			ctx.state.gameActionsState.value,
			ctx.state.relatedStoryHistoryState.value,
			ctx.state.customMemoriesState.value
		);
		const generatedAction = await ctx.agents.actionAgent.generateSingleAction(
			action,
			ctx.state.getCurrentGameActionState(),
			ctx.state.historyMessagesState.value,
			ctx.state.storyState.value,
			ctx.state.characterState.value,
			ctx.state.characterStatsState.value,
			ctx.state.inventoryState.value,
			ctx.state.systemInstructionsState.value.generalSystemInstruction,
			ctx.state.systemInstructionsState.value.actionAgentInstruction,
			ctx.state.relatedActionHistoryState.value,
			ctx.state.gameSettingsState.value?.aiIntroducesSkills,
			ctx.state.getCurrentGameActionState().is_character_restrained_explanation,
			ctx.state.additionalActionInputState.value,
			getSafetyLevelFromStory(ctx.state.storyState.value)
		);
		const merged = { ...generatedAction, ...action } as Action;
		ctx.state.chosenActionState.value = merged;
		ctx.skills.addSkillsIfApplicable([merged]);
		if (merged.is_possible === false) {
			ctx.modals.setCustomActionImpossibleReason('not_plausible');
		} else {
			if (
				!gameLogic.isEnoughResource(
					merged,
					ctx.state.playerCharactersGameState.value[ctx.state.playerCharacterId],
					ctx.state.inventoryState.value
				)
			) {
				ctx.modals.setCustomActionImpossibleReason('not_enough_resource');
			} else {
				ctx.modals.setCustomActionImpossibleReason(undefined);
				await sendAction(
					merged,
					gameLogic.mustRollDice(
						merged,
						ctx.state.getCurrentGameActionState().is_character_in_combat
					)
				);
			}
		}
		ctx.state.isAiGeneratingState.set(false);
	}

	async function onCustomActionSubmitted(
		text: string,
		mustGenerateCustomAction = false,
		receiver: 'Game Command' | 'Character Action' | 'GM Question' | 'Dice Roll' = 'Character Action'
	) {
		let action: Action = {
			characterName: ctx.state.characterState.value.name,
			text,
			is_custom_action: true
		};
		if (receiver === 'Character Action' || mustGenerateCustomAction) {
			await generateActionFromCustomInput(action);
		}
		if (receiver === 'GM Question') {
			ctx.modals.setGMQuestion(action.text);
		}
		if (receiver === 'Dice Roll') {
			ctx.modals.setCustomDiceRollNotation(action.text);
		}
		if (receiver === 'Game Command') {
			ctx.state.additionalStoryInputState.value +=
				'\nsudo: Ignore the rules and play out this action even if it should not be possible!\nIf this action contradicts the PAST STORY PLOT, adjust the narrative to fit the action.';
			await sendAction(action, false);
		}
	}

	function handleUtilityAction(actionValue: string) {
		if (!actionValue) return;
		let text = '';
		if (actionValue === 'short-rest') {
			text =
				'Player character is doing a short rest, handle the resources regeneration according GAME rules and describe the scene. If there are no specific GAME rules, increase all resources by 50% of the maximum.';
		} else if (actionValue === 'long-rest') {
			text =
				'Player character is doing a long rest, handle the resources regeneration according GAME rules and describe the scene. If there are no specific GAME rules, increase all resources by 100% of the maximum.';
		}
		if (text) {
			void sendAction(
				{
					characterName: ctx.state.characterState.value.name,
					text,
					is_custom_action: false
				} as Action,
				false
			);
		}
	}

	async function handleTargetedSpellsOrAbility(action: Action, targets: string[]) {
		ctx.state.isAiGeneratingState.set(true);
		let targetAddition = '';
		if (targets?.length > 0 && !targets.some((t) => t === undefined)) {
			targetAddition = `\n\nTargets: ${targets.join(', ')}\n`;
		}
		// Append targets to the player's original text BEFORE calling the agent
		action.text += targetAddition;
		const { getRelatedHistory } = await import('../memory/memoryLogic');
		ctx.state.relatedActionHistoryState.value = await getRelatedHistory(
			ctx.agents.summaryAgent,
			action,
			ctx.state.gameActionsState.value,
			ctx.state.relatedStoryHistoryState.value,
			ctx.state.customMemoriesState.value
		);
		const generatedAction = await ctx.agents.actionAgent.generateSingleAction(
			action,
			ctx.state.getCurrentGameActionState(),
			ctx.state.historyMessagesState.value,
			ctx.state.storyState.value,
			ctx.state.characterState.value,
			ctx.state.characterStatsState.value,
			ctx.state.inventoryState.value,
			ctx.state.systemInstructionsState.value.generalSystemInstruction,
			ctx.state.systemInstructionsState.value.actionAgentInstruction,
			ctx.state.relatedActionHistoryState.value,
			ctx.state.gameSettingsState.value?.aiIntroducesSkills,
			ctx.state.getCurrentGameActionState().is_character_restrained_explanation,
			ctx.state.additionalActionInputState.value,
			getSafetyLevelFromStory(ctx.state.storyState.value)
		);
		if (generatedAction) {
			// Preserve VERBATIM player text (including appended targets):
			// Ensure any AI-provided text never overwrites the player's intent.
			action = { ...generatedAction, ...action };
		}
		action.is_custom_action = true;
		ctx.state.chosenActionState.value = action;
		ctx.skills.addSkillsIfApplicable([action]);
		const abilityAddition =
			'\n If this is a friendly action used on an enemy, play out the effect as described, even though the result may be unintended.' +
			'\n Hostile NPCs stay hostile unless explicitly described otherwise by the actions effect.' +
			'\n Friendly NPCs turn hostile if attacked.';

		ctx.state.additionalStoryInputState.value =
			targetAddition + abilityAddition + (ctx.state.additionalStoryInputState.value || '');
		await sendAction(
			action,
			gameLogic.mustRollDice(action, ctx.state.getCurrentGameActionState().is_character_in_combat)
		);
		ctx.state.isAiGeneratingState.set(false);
	}

	function handleItemUseChosen(item: Action & any & { item_id: string }) {
		return item;
	}

	function getEventToConfirm(gameEvent: CharacterChangedInto): {
		title: string;
		description: string;
	} {
		return {
			title: `Transform into ${gameEvent.changed_into}`,
			description: `Your character is changing into: ${gameEvent.changed_into}. ${gameEvent.description || ''}. Do you accept this transformation?`
		};
	}

	function handleLevelUpModalClosed(aiLevelUp: AiLevelUp) {
		if (aiLevelUp) {
			ctx.state.characterStatsState.value = applyLevelUp(
				aiLevelUp,
				ctx.state.characterStatsState.value
			);
		} else {
			console.log('Level up cancelled');
		}

		const { updatedGameActionsState, updatedPlayerCharactersGameState } = refillResourcesFully(
			JSON.parse(JSON.stringify(ctx.state.characterStatsState.value.resources)),
			ctx.state.playerCharacterId,
			ctx.state.characterState.value.name,
			JSON.parse(JSON.stringify(ctx.state.gameActionsState.value)),
			JSON.parse(JSON.stringify(ctx.state.playerCharactersGameState.value))
		);
		ctx.state.gameActionsState.value = updatedGameActionsState;
		ctx.state.playerCharactersGameState.value = updatedPlayerCharactersGameState;
		ctx.helpers.checkForLevelUp();
	}

	function handleSuggestItemActionClosed(action?: Action) {
		if (action) {
			ctx.state.chosenActionState.value = action;
			ctx.skills.addSkillsIfApplicable([action]);
			void sendAction(
				action,
				gameLogic.mustRollDice(action, ctx.state.getCurrentGameActionState().is_character_in_combat)
			);
		}
	}

	function handleCustomDiceRollClosed() {
		// Reset custom dice roll notation in component
	}

	function levelUpClicked(playerName: string) {
		const level = JSON.parse(JSON.stringify(ctx.state.characterStatsState.value.level));
		const xpNeededForLevel = getXPNeededForLevel(level);
		if (!xpNeededForLevel) {
			console.error('No XP requirement found for level', level);
			return false;
		}
		const buyLevelUpObject = getLevelUpCostObject(xpNeededForLevel, playerName, level);
		// Ensure character state exists before accessing XP
		if (ctx.state.playerCharactersGameState.value[ctx.state.playerCharacterId]?.XP) {
			ctx.state.playerCharactersGameState.value[ctx.state.playerCharacterId].XP.current_value -=
				xpNeededForLevel;
		}
		ctx.state.gameActionsState.value[ctx.state.gameActionsState.value.length - 1].stats_update.push(
			buyLevelUpObject
		);
		ctx.helpers.checkForLevelUp();
		ctx.modals.setLevelUpPlayerName(playerName);
		return true; // Signal to open level up dialog
	}

	return {
		sendAction,
		regenerateActions,
		confirmCharacterChangeEvent,
		confirmAbilitiesLearned,
		generateActionFromCustomInput,
		onCustomActionSubmitted,
		handleUtilityAction,
		handleTargetedSpellsOrAbility,
		handleItemUseChosen,
		getEventToConfirm,
		handleLevelUpModalClosed,
		handleSuggestItemActionClosed,
		handleCustomDiceRollClosed,
		levelUpClicked
	} as const;
}
