<script lang="ts">
	import '../app.css';
	import discord from '$lib/assets/socials/discord-logo-blue.png';
	import github from '$lib/assets/socials/icone-github-jaune.png';
	import logo from '$lib/assets/logo-removebg.png';
	import Disclaimer from '$lib/components/ui/layout/Disclaimer.svelte';
	import { goto } from '$app/navigation';

	let disclaimerOpen = $state(false);
</script>

<main class="min-h-screen">
	<!-- Hero Section -->
	<div class="hero from-base-100 to-base-200 min-h-screen bg-gradient-to-br">
		<div class="hero-content text-center">
			<div class="max-w-4xl">
				<div class="mb-8">
					<img src={logo} alt="Infinite Tales Logo" class="mx-auto w-32 sm:w-48 md:w-64" />
				</div>

				<div class="mb-6">
					<div class="badge badge-primary badge-lg mb-4">🎮 AI-Powered RPG</div>
				</div>

				<h1
					class="from-primary to-secondary mb-6 bg-gradient-to-r bg-clip-text text-4xl font-bold text-transparent sm:text-5xl md:text-6xl"
				>
					Shape Your Unique Tale
				</h1>

				<p class="text-base-content/80 mx-auto mb-6 max-w-3xl text-lg sm:text-xl">
					Infinite Tales RPG is a Choose Your Own Adventure Text RPG, dynamically narrated by AI.
				</p>

				<p class="text-base-content/70 mx-auto mb-6 max-w-2xl">
					Customize every aspect of your adventure. Build your hero, explore vast lands, and make
					crucial decisions that determine your fate. Each adventure is uniquely generated by
					roleplaying AI, ensuring that no two journeys are alike.
				</p>

				<p class="text-base-content/70 mx-auto mb-8 max-w-2xl">
					Let your custom Pen and Paper adventure in any game system like Dungeons and Dragons be
					guided by the AI Game Master.
				</p>

				<!-- Feature Cards Grid -->
				<div class="mx-auto mb-8 grid max-w-4xl grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
					<div class="card bg-base-200 shadow-md">
						<div class="card-body items-center p-4 text-center">
							<div class="badge badge-warning mb-2">In Development</div>
							<h3 class="card-title text-sm">Character Stats</h3>
							<p class="text-base-content/70 text-xs">Define your hero's strengths</p>
						</div>
					</div>

					<div class="card bg-base-200 shadow-md">
						<div class="card-body items-center p-4 text-center">
							<div class="badge badge-info mb-2">🎲</div>
							<h3 class="card-title text-sm">Dice Rolls</h3>
							<p class="text-base-content/70 text-xs">Thrill of chance and strategy</p>
						</div>
					</div>

					<div class="card bg-base-200 shadow-md">
						<div class="card-body items-center p-4 text-center">
							<div class="badge badge-success mb-2">✨</div>
							<h3 class="card-title text-sm">Skills & Abilities</h3>
							<p class="text-base-content/70 text-xs">Unique tailored abilities</p>
						</div>
					</div>

					<div class="card bg-base-200 shadow-md">
						<div class="card-body items-center p-4 text-center">
							<div class="badge badge-accent mb-2">📈</div>
							<h3 class="card-title text-sm">Character Progression</h3>
							<p class="text-base-content/70 text-xs">Grow throughout the story</p>
						</div>
					</div>

					<div class="card bg-base-200 shadow-md">
						<div class="card-body items-center p-4 text-center">
							<div class="badge badge-error mb-2">⚔️</div>
							<h3 class="card-title text-sm">Combat System</h3>
							<p class="text-base-content/70 text-xs">Dynamic tactical battles</p>
						</div>
					</div>

					<div class="card bg-base-200 shadow-md">
						<div class="card-body items-center p-4 text-center">
							<div class="badge badge-secondary mb-2">🚀</div>
							<h3 class="card-title text-sm">AI Narration</h3>
							<p class="text-base-content/70 text-xs">Dynamic storytelling</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="divider"></div>

	<div class="divider"></div>

	<!-- How to Start Playing Section -->
	<section class="px-6 py-16">
		<div class="container mx-auto max-w-4xl">
			<div class="mb-12 text-center">
				<h2 class="mb-4 text-3xl font-bold sm:text-4xl">How to Start Playing</h2>
				<div class="badge badge-success badge-lg mb-6">🆓 Free to Play</div>
			</div>

			<div class="card bg-base-200 shadow-xl">
				<div class="card-body text-center">
					<div class="mb-6">
						<div class="badge badge-primary mb-4">Step 1</div>
						<h3 class="card-title mb-4 justify-center text-xl">Get Your Google Gemini API Key</h3>
						<p class="text-base-content/80 mb-4">
							To begin your tale, you need a Google Gemini API Key. It's free and easy to set up!
						</p>
					</div>

					<div class="alert alert-info mb-6">
						<svg
							xmlns="http://www.w3.org/2000/svg"
							fill="none"
							viewBox="0 0 24 24"
							class="h-6 w-6 shrink-0 stroke-current"
							><path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
							></path></svg
						>
						<div>
							<div class="text-sm">
								Your key is only stored in your browser, ensuring your privacy.
							</div>
						</div>
					</div>

					<div class="card-actions justify-center">
						<a
							target="_blank"
							href="https://github.com/JayJayBinks/infinite-tales-rpg/wiki/Create-your-free-Google-Gemini-API-Key-%F0%9F%94%91"
							class="btn btn-primary"
						>
							📖 View Setup Guide
						</a>
					</div>
				</div>
			</div>
		</div>
	</section>

	<div class="divider"></div>

	<!-- Join Beta Section -->
	<section class="from-primary/10 to-secondary/10 bg-gradient-to-r px-6 py-16">
		<div class="container mx-auto max-w-2xl text-center">
			<div class="mb-6">
				<div class="badge badge-accent badge-lg mb-4">🚀 Beta Access</div>
				<h2 class="mb-4 text-3xl font-bold sm:text-4xl">Join the Beta</h2>
				<p class="text-base-content/80 mb-8 text-lg">
					Experience the game in the early stages and help shape its future.
				</p>
			</div>

			<button class="btn btn-primary btn-lg gap-2" onclick={() => (disclaimerOpen = true)}>
				<span>🎮</span>
				Start Your Tale
			</button>
		</div>
	</section>

	<div class="divider"></div>

	<div class="divider"></div>

	<!-- Contact Section -->
	<section class="px-6 py-16">
		<div class="container mx-auto max-w-6xl">
			<div class="mb-12 text-center">
				<h2 class="mb-4 text-3xl font-bold sm:text-4xl">Connect With Us</h2>
				<p class="text-base-content/70 text-lg">Join our community and stay updated</p>
			</div>

			<div class="mx-auto grid max-w-4xl grid-cols-1 gap-8 md:grid-cols-2">
				<!-- Discord Card -->
				<div class="card bg-base-200 shadow-xl transition-shadow hover:shadow-2xl">
					<figure class="px-8 pt-8">
						<img class="h-20 w-20" src={discord} alt="Discord Logo" />
					</figure>
					<div class="card-body text-center">
						<h3 class="card-title justify-center">Community Discussion</h3>
						<p class="text-base-content/70">
							Join our Discord server for real-time discussions, feedback, and community support.
						</p>
						<div class="card-actions mt-4 justify-center">
							<a target="_blank" href="https://discord.gg/CUvgRQR77y" class="btn btn-primary gap-2">
								<span>💬</span>
								Join Discord
							</a>
						</div>
					</div>
				</div>

				<!-- GitHub Card -->
				<div class="card bg-base-200 shadow-xl transition-shadow hover:shadow-2xl">
					<figure class="px-8 pt-8">
						<img class="h-20 w-20" src={github} alt="GitHub Logo" />
					</figure>
					<div class="card-body text-center">
						<h3 class="card-title justify-center">Source Code</h3>
						<p class="text-base-content/70">
							Explore the codebase, contribute, report issues, or fork the project on GitHub.
						</p>
						<div class="card-actions mt-4 justify-center">
							<a
								target="_blank"
								href="https://github.com/JayJayBinks/infinite-tales-rpg"
								class="btn btn-accent gap-2"
							>
								<span>⭐</span>
								View on GitHub
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<div class="divider"></div>

	<!-- Open Source Section -->
	<section class="from-accent/10 to-primary/10 bg-gradient-to-r px-6 py-16">
		<div class="container mx-auto max-w-4xl text-center">
			<div class="mb-6">
				<div class="badge badge-accent badge-lg mb-4">🌟 Open Source</div>
				<h2 class="mb-4 text-3xl font-bold sm:text-4xl">Built by the Community</h2>
				<p class="text-base-content/80 mx-auto max-w-2xl text-lg">
					Infinite Tales RPG is an open-source project, licensed under the GNU AGPLv3 License. Join
					us in shaping the future of AI-powered RPGs.
				</p>
			</div>
		</div>
	</section>

	<div class="divider"></div>
	<div class="divider"></div>

	<!-- Acknowledgements Section -->
	<section class="px-6 py-16">
		<div class="container mx-auto max-w-6xl">
			<div class="mb-12 text-center">
				<h2 class="mb-4 text-3xl font-bold sm:text-4xl">Acknowledgements</h2>
				<p class="text-base-content/70 text-lg">
					Thanks to the amazing tools and services that make this possible
				</p>
			</div>

			<div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4">
				<!-- RPG Prompts Card -->
				<div class="card bg-base-200 shadow-lg transition-shadow hover:shadow-xl">
					<div class="card-body p-6 text-center">
						<div class="badge badge-primary mb-3">🎲 Prompts</div>
						<h3 class="mb-2 font-semibold">RPG Prompts</h3>
						<p class="text-base-content/70 mb-4 text-sm">
							Prompt magicians providing the core game experience
						</p>
						<a class="link link-primary text-sm" href="https://www.rpgprompts.com/" target="_blank">
							Visit rpgprompts.com
						</a>
					</div>
				</div>

				<!-- Pollinations Card -->
				<div class="card bg-base-200 shadow-lg transition-shadow hover:shadow-xl">
					<div class="card-body p-6 text-center">
						<div class="badge badge-secondary mb-3">🎨 Images</div>
						<h3 class="mb-2 font-semibold">Pollinations AI</h3>
						<p class="text-base-content/70 mb-4 text-sm">
							Amazing AI-powered image generation service
						</p>
						<a class="link link-secondary text-sm" href="https://pollinations.ai/" target="_blank">
							Visit pollinations.ai
						</a>
					</div>
				</div>

				<!-- 3D Dice Card -->
				<div class="card bg-base-200 shadow-lg transition-shadow hover:shadow-xl">
					<div class="card-body p-6 text-center">
						<div class="badge badge-accent mb-3">🎲 Dice</div>
						<h3 class="mb-2 font-semibold">3D Dice Box</h3>
						<p class="text-base-content/70 mb-4 text-sm">
							Cool 3D dice rolling animations and physics
						</p>
						<a
							class="link link-accent text-sm"
							href="https://github.com/3d-dice/dice-box"
							target="_blank"
						>
							View on GitHub
						</a>
					</div>
				</div>

				<!-- Icons8 Card -->
				<div class="card bg-base-200 shadow-lg transition-shadow hover:shadow-xl">
					<div class="card-body p-6 text-center">
						<div class="badge badge-info mb-3">🎯 Icons</div>
						<h3 class="mb-2 font-semibold">Icons8</h3>
						<p class="text-base-content/70 mb-4 text-sm">Beautiful favicon and icon designs</p>
						<a class="link link-info text-sm" href="https://icons8.com" target="_blank">
							Visit icons8.com
						</a>
					</div>
				</div>
			</div>
		</div>
	</section>

	<!-- Footer -->
	<footer class="footer footer-center bg-base-200 text-base-content p-10">
		<div>
			<img src={logo} alt="Infinite Tales Logo" class="h-16 w-16" />
			<p class="font-bold">
				Infinite Tales RPG <br />
				<span class="badge badge-ghost">AI-Powered Adventures</span>
			</p>
			<p class="text-base-content/70">Copyright © 2024 - Licensed under GNU AGPLv3</p>
		</div>
	</footer>

	<!-- Disclaimer Modal -->
	<Disclaimer
		{disclaimerOpen}
		onAgree={() => {
			disclaimerOpen = false;
			goto('game/settings/ai');
		}}
	></Disclaimer>
</main>
