/**
 * Campaign format prompts
 */

/**
 * Format for campaign chapters in prompts
 */
export const chaptersPrompt = `{
		"chapterId": number,
		"title": string,
		"description": string,
		"objective": string,
		"plot_points": [
			{
				"plotId": always start at 1 again for each new chapter,
				"location": string,
				"description": string,
				"objective": string,
				"important_NPCs": String Array; No object, just one descriptive String per NPC that are important to this plot point,
				"game_master_notes": string array; rules how specific obstacles must be solved by the player; e.g an enemy can only be damaged by fire; a specific spell is required to disarm a magical lock;
			},
			...
		]
	}`;

/**
 * Complete campaign JSON format prompt
 */
export const campaignJsonPrompt = `{
	"game": "Pick Any Pen & Paper System e.g. Pathfinder, Call of Cthulhu, Star Wars, Fate Core, World of Darkness, GURPS, Mutants & Masterminds, Dungeons & Dragons",
	"campaign_title": string,
	"campaign_description": string,
	"world_details": "Provide a vivid and in-depth description of the world's important details, including its geography, cultures, history, key events, technologies, political systems, and any unique elements that set it apart. Ensure the description creates an immersive setting that supports and enhances storytelling.",
	"character_simple_description": String; Generate a random character fitting the game system, world_details and campaignDescription, only provide a simple description and not every detail,
	"general_image_prompt": "Create a general system prompt max 10 words for this campaign to add to every image that is generated by an ai. Format: {visualStyle} {genre} {artistReference}",
	"theme": 'THEME of the story telling, e.g. world the story is located in',
	"tonality": 'TONALITY of the story telling, writing style, must fit GAME system',
	"chapters": [
		${chaptersPrompt},
		...
	]
}`;

/**
 * Number of plot points per chapter
 */
export const plotPointNumberPrompt = 'Each chapter with 2 - 4 plot points';
