import { getRandomInteger, stringifyPretty } from '$lib/util.svelte';
import type { LLM, LLMRequest } from '$lib/ai/llm';
import type { CharacterDescription } from '$lib/ai/agents/characterAgent';
import isEqual from 'lodash.isequal';

export type Story = typeof storyStateForPrompt;

export const exampleGameSystems = [
	'Pathfinder',
	'Call of Cthulhu',
	'Star Wars',
	'Fate Core',
	'Harry Potter',
	'Discworld',
	'World of Darkness',
	'GURPS',
	'Mutants & Masterminds',
	'Dungeons & Dragons'
];

export const TROPES_CLICHE_PROMPT =
	'Create a unique world with fresh names, avoiding clichés, generic prefixes, and overused tropes;\n';

// stringifyPretty(storyStateForPrompt) works because no json included in the values
//TODO if we remove this as object new tale form placeholder wont work anymore...
export const storyStateForPrompt = {
	game: 'Any Pen & Paper System e.g. Pathfinder, Call of Cthulhu, Star Wars, Fate Core, World of Darkness, GURPS, Mutants & Masterminds, Dungeons & Dragons',
	world_details:
		"Provide a concise yet vivid description of the world's key characteristics, highlighting its most distinctive features such as geography, culture, history, or any unique elements that define its essence. Focus on creating a snapshot that inspires and supports storytelling.",
	adventure_and_main_event:
		'Generate a random adventure with a random main story line. It does not have to be a quest, it can also be an event. It should be extraordinary and not cliche.',
	character_simple_description:
		'Generate a random character fitting the GAME system in ADVENTURE_AND_MAIN_EVENT, only provide a simple description as string nd not every detail',
	general_image_prompt:
		'Create a general system prompt max 10 words for this adventure to add to every image that is generated by an ai. Format: {visualStyle} {genre} {artistReference}',
	theme: 'THEME of the story telling, e.g. world the story is located in',
	tonality: 'TONALITY of the story telling, writing style, must fit GAME system',
	background_event:
		'Generate a background event that colors the setting (festival, war, crisis, rumor, political tension, natural phenomenon, etc.). This should create atmosphere and context for the story without being the main focus.',
	social_dynamics:
		'Describe the social circles, factions, rivalries, or tensions that structure daily life. Include power dynamics, social hierarchies, or conflicts that could influence character interactions and story development.',
	locations:
		'List 2-3 everyday locations where characters might frequent (tavern, marketplace, guild hall, etc.) plus one special or mysterious place that could serve as an adventure site. Provide brief but evocative descriptions.',
	npcs: 'Create 3-4 secondary characters (friends, rivals, mentors, contacts) with simple motivations and relationship to the main character. Include their role, personality traits, and what they want or need.',
	adventure_hook:
		'Define the initial situation that serves as the starting point for the adventure. This should be compelling, clear, and provide obvious reasons for character involvement without being overly complex.',
	trigger_event:
		'Describe a small unexpected element that can relaunch the story or break routine when needed. This should be a plot device that can escalate tension, introduce complications, or shift story direction.',
	evolution:
		'Explain how the narrative can transition from slice-of-life to adventure (or vice versa). Describe the escalation path and how everyday situations can develop into larger conflicts or how adventures can settle into quieter periods.',
	consequences:
		'Outline what changes if characters act versus remain passive. Describe the stakes, potential outcomes, and how character choices will meaningfully impact the world and story progression.',
	content_rating:
		'Specify content boundaries: safe (family-friendly), mid (mild mature themes), adult (mature themes and violence), or uncensored (no content restrictions). This sets tone and content limits for story generation.',
	tags: 'Provide a short list of 4-6 keywords describing genres, sub-genres, themes, or mood (e.g., dark fantasy, political intrigue, mystery, romance, comedy, survival, etc.). These guide story tone and content.'
};

export const initialStoryState: Story = {
	game: '',
	world_details: '',
	adventure_and_main_event: '',
	character_simple_description: '',
	general_image_prompt: '',
	theme: '',
	tonality: '',
	background_event: '',
	social_dynamics: '',
	locations: '',
	npcs: '',
	adventure_hook: '',
	trigger_event: '',
	evolution: '',
	consequences: '',
	content_rating: '',
	tags: ''
};

export class StoryAgent {
	llm: LLM;

	constructor(llm: LLM) {
		this.llm = llm;
	}

	async generateRandomStorySettings(
		overwrites = {},
		characterDescription: CharacterDescription | undefined = undefined
	): Promise<Story> {
		const storyAgent =
			'You are RPG story agent, crafting captivating, limitless GAME experiences using BOOKS, THEME, TONALITY for CHARACTER.\n' +
			TROPES_CLICHE_PROMPT +
			'Always respond with following JSON!\n' +
			stringifyPretty(storyStateForPrompt);

		const preset = {
			...storyStateForPrompt,
			...overwrites
		};
		if (isEqual(overwrites, {}) && characterDescription === undefined) {
			preset.game = exampleGameSystems[getRandomInteger(0, exampleGameSystems.length - 1)];
		}
		const request: LLMRequest = {
			userMessage:
				'Create a new randomized story considering the following settings: ' +
				stringifyPretty(preset),
			historyMessages: [],
			systemInstruction: storyAgent
		};
		if (characterDescription) {
			request.historyMessages?.push({
				role: 'user',
				content:
					'Set following to character_simple_description; The adventure_and_main_event must be based on this;\n' +
					stringifyPretty(characterDescription)
			});
		}
		return (await this.llm.generateContent(request))?.content as Story;
	}
}
